on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
jobs: 
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-8)
          if [ "$GITHUB_REF_TYPE" == "tag" ]; then
            IMAGE_TAG=$GITHUB_REF_NAME
          fi
          echo "Build with tag $IMAGE_TAG
  sync:
    if: ${{ github.ref_type	== 'tag' }} 
    name: Sync
    runs-on: ubuntu-22.04
    steps:
      - name: Update config
        run: echo "Update config ${{ inputs.service }}"
      - name: Sync config
        run: echo "Sync config ${{ inputs.service }}"
      
