on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
jobs: 
  sync-dev:
    if: ${{ github.ref_name == 'main' }}
    name: Sync Dev
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - name: Update config
        run: echo "sync dev ${{ inputs.service }}"
  sync-staging:
    if: ${{ github.ref_type	== 'tag' }} 
    name: Sync Staging
    runs-on: ubuntu-22.04
    environment: staging
    steps:
      - name: Update config
        run: echo "sync staging ${{ inputs.service }}"
  sync-prod:
    if: ${{ github.ref_type	== 'tag' }} 
    name: Sync Prod
    runs-on: ubuntu-22.04
    environment: prod
    steps:
      - name: Update config
        run: echo "sync prod ${{ inputs.service }}"
